### ISSUE TITLE
权限校验问题

### ISSUE THREAD

**Issue by KuiShang** [xu455255849/myBlog#2]
文章详情里  
`admin: localStorage.getItem('username') === '徐绍平'`
这样不全安啊，我在本地写了一个同样的key，结果竟然可以弹出删除modal，这一块楼主还要考虑一下

**Comment by xu455255849** [comment]
谢谢提醒，放出源码是交流学习。这个其实不是不安全，是你看到了我的源码。如果你看不到源码，你应该是猜不到管理员的账号的。你在服务器脚本还能看到我的服务器root账号，这些会暴露在源码里／是没法避免的。所以源码不能泄漏。

**Comment by xu455255849** [comment]
你要把数据库链接到你的数据库，然后  你可以使用你自己喜欢的加密方式，源码不泄漏，安全问题应该是有保障的。
我都写了比较详细的教程～
`var db = require('mongoskin').db('mongodb://xu:1314loveWMM@localhost:27017/blog?authSource=admin');`

**Comment by KuiShang** [comment]
po主厉害 共勉 哈哈~~
